### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by Prudhvinik1** [NVIDIA/ContrastiveLosses4VRD#3]
Traceback (most recent call last):
  File "tools/train_net_step_rel.py", line 31, in <module>
    from modeling_rel.model_builder_rel import Generalized_RCNN
  File "/content/ContrastiveLosses4VRD/lib/modeling_rel/model_builder_rel.py", line 17, in <module>
    from model.roi_pooling.functions.roi_pool import RoIPoolFunction
  File "/content/ContrastiveLosses4VRD/Detectron_pytorch/lib/model/roi_pooling/functions/roi_pool.py", line 3, in <module>
    from .._ext import roi_pooling
  File "/content/ContrastiveLosses4VRD/Detectron_pytorch/lib/model/roi_pooling/_ext/roi_pooling/__init__.py", line 3, in <module>
    from ._roi_pooling import lib as _lib, ffi as _ffi
ImportError: /content/ContrastiveLosses4VRD/Detectron_pytorch/lib/model/roi_pooling/_ext/roi_pooling/_roi_pooling.so: undefined symbol: __cudaPopCallConfiguration

Could you help me figure out this error?

**Comment by ChandanVerma** [comment]
This error usually arrives due to the mismath in the cuda version installed on the system and cuda version working in your environment.
You might have CUDA 10.0 configured on your system and you are using CUDA 9.x in your working environment
